version: '3.4'

services:
  frontend:
    image: frontend
    build:
      context: frontend
      dockerfile: ./Dockerfile
      target: dev
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_BASE_ROUTE: http://127.0.0.1:3000
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - db
      - backend
  backend:
    image: backend
    build:
      context: backend
      dockerfile: ./Dockerfile
      target: dev
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: devdb
      POSTGRES_PASSWORD: secret123
      POSTGRES_USER: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
